project:
  type: website
  output-dir: docs

website:
  title: "Jeffrey Hsu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Quarto Dashboard
      - href: shiny-app.qmd
        text: Shiny App
      - href: shinylive-essay.qmd
        text: Shinylive Essay

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-expand: true
    embed-resources: true
    code-fold: true
    code-tools: true
